alpha: 0.0
batch_size: 30
beam_size: 5
beta: -0.0
block_ngram_repeat: 0
coverage_penalty: none
data_type: text
dump_beam: ''
dynamic_dict: 'true'
gpu: 0
ignore_when_blocking: []
image_channel_size: 3
length_penalty: none
log_file: ''
log_file_level: '0'
max_length: 100
min_length: 0
model:
- model-copy_step_10000.pt
n_best: 1
output: pred_copy.txt
phrase_table: ''
random_sampling_temp: 1.0
random_sampling_topk: 1
ratio: -0.0
sample_rate: 16000
seed: 829
shard_size: 10000
share_vocab: 'true'
src: data/src-test.txt
src_dir: ''
window: hamming
window_size: 0.02
window_stride: 0.01
