data_type: text
dynamic_dict: 'true'
features_vocabs_prefix: ''
image_channel_size: 3
log_file: ''
log_file_level: '0'
max_shard_size: 0
report_every: 100000
sample_rate: 16000
save_data: data/newsela
seed: 3435
shard_size: 1000000
share_vocab: 'true'
shuffle: 0
src_dir: ''
src_seq_length: 50
src_vocab: ''
src_vocab_size: 50000
src_words_min_frequency: 0
tgt_seq_length: 50
tgt_vocab: ''
tgt_vocab_size: 50000
tgt_words_min_frequency: 0
train_src: data/src-train.txt
train_tgt: data/tgt-train.txt
valid_src: data/src-val.txt
valid_tgt: data/tgt-val.txt
vocab_size_multiple: 1
window: hamming
window_size: 0.02
window_stride: 0.01
